### ISSUE TITLE
1.1.5.5 Crash when attempting to paste data into CC nodes

### ISSUE THREAD

**Issue by ErikHoggard** [Nornec/Midinous-Issues#39]
Steps to reproduce:

1. Select a note or a logic gate 
2. click the "copy this point's data to a clipboard" button
3. Select a CC node (or a group of nodes containing at least one CC node and at least one of another type, which is how I discovered this)
4. Click the paste button

It seems like copy/pasting data into CC nodes doesn't work at all. I'm not sure if this is another bug, or just something that isn't implemented yet.

**Comment by Nornec** [comment]
Bug confirmed! It's trying to paste a note point's data to CC point's data object. Expected crash. I'll have a fix out for this, thank you for finding this!

**Comment by Nornec** [comment]
For more reference this is the crash log:
`2023-5.28.15.1.7 Exception occurred: Unable to cast object of type 'Midinous.Placeable.NotePoint' to type 'Midinous.Placeable.CCPoint'.
2023-5.28.15.1.7 Caught exception:System.InvalidCastException: Unable to cast object of type 'Midinous.Placeable.NotePoint' to type 'Midinous.Placeable.CCPoint'.
   at Midinous.Static.UserInterface.<>c.<define_button_events>b__487_6(Object obj, EventArgs args)
   at Myra.Graphics2D.UI.Container.OnTouchUp()
   at Myra.Graphics2D.UI.ButtonBase`1.OnTouchUp()
   at Myra.Utility.InputHelpers.ProcessTouchUp(List`1 widgets)
   at Myra.Utility.InputHelpers.ProcessTouchUp(List`1 widgets)
   at Myra.Utility.InputHelpers.ProcessTouchUp(List`1 widgets)
   at Myra.Utility.InputHelpers.ProcessTouchUp(List`1 widgets)
   at Myra.Utility.InputHelpers.ProcessTouchUp(List`1 widgets)
   at Myra.Utility.InputHelpers.ProcessTouchUp(List`1 widgets)
   at Myra.Utility.InputHelpers.ProcessTouchUp(List`1 widgets)
   at Myra.Utility.InputHelpers.ProcessTouchUp(List`1 widgets)
   at Myra.Graphics2D.UI.Desktop.UpdateMouseInput()
   at Myra.Graphics2D.UI.Desktop.UpdateInput()
   at Myra.Graphics2D.UI.Desktop.Render()
   at Midinous.Base.Midinous.Draw(GameTime progTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Midinous.Base.Program.Main()
2023-5.28.15.1.7 There was an unexpected problem at entry point Program.Main() and the program must close.
`

**Comment by Nornec** [comment]
Fixed in upcoming 1.1.5.6
