### ISSUE TITLE
Crashes on Launch. CoreCLR System.AccessViolationException

### ISSUE THREAD

**Issue by josephToke** [Nornec/Midinous-Issues#41]
Nothing useful in midinous logs. Running Latest release on steam: 1.1.5.5

``Faulting application name: Midinous.exe, version: 1.1.5.5, time stamp: 0x63ed82c1
Faulting module name: coreclr.dll, version: 7.0.423.11508, time stamp: 0x63ed7a18
Exception code: 0xc0000005
Fault offset: 0x00000000001ca906
Faulting process id: 0x2628
Faulting application start time: 0x01d991ffee39142f
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\Midinous\Midinous.exe
Faulting module path: C:\Program Files (x86)\Steam\steamapps\common\Midinous\coreclr.dll
Report Id: 1db1a487-0c1a-49ce-8a08-7d19a3283728
Faulting package full name: 
Faulting package-relative application ID: ``

``Application: Midinous.exe
CoreCLR Version: 7.0.423.11508
.NET Version: 7.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at Sdl+Window.Create(System.String, Int32, Int32, Int32, Int32, Int32)
   at Microsoft.Xna.Framework.SdlGameWindow.CreateWindow()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.PlatformInitialize(Microsoft.Xna.Framework.Graphics.PresentationParameters)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Initialize(Microsoft.Xna.Framework.GraphicsDeviceInformation)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(Microsoft.Xna.Framework.GameRunBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Midinous.Base.Program.Main()
``

Tried running legacy version but similar exception occurs: 
``Application: Midinous.exe
CoreCLR Version: 4.700.22.51102
.NET Core Version: 3.1.31
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFA8DAC2659 (00007FFA8D930000) with exit code c0000005.
``

Windows 10 KVM Virtual Machine
Ryzen 7 5700G
32 GB
Radeon RX 470 Passed through to vm

**Comment by Nornec** [comment]
Looks like your VM is missing graphics drivers for OpenGL

**Comment by Nornec** [comment]
Any specific reason you are running through a VM?

**Comment by Nornec** [comment]
Great to hear! Enjoy the program.
