### ISSUE TITLE
crash when options are opened

### ISSUE THREAD

**Issue by catarial** [Nornec/Midinous-Issues#65]
OS: Alpine Linux 3.20 x86_64 (steam flatpak)

Midinous crashes when the options are opened.

```
>>>>>>>>2024-07-01-02.17.43 Midinous session startup commencing. This is an error log.
>>>>>>>>2024-07-01-02.17.43 Release - 1.2.0.1
2024-07-01-02.17.43 Could not read data from /home/tacocat/.local/share/Midinous/user/settings.json
2024-07-01-02.17.43 Exception caught: The type initializer for 'Midinous.MIDI.MIDIInfo' threw an exception.
2024-07-01-02.17.43 BMIDI bus driver is not installed.
2024-07-01-02.17.43 Bad return code setting up MIDI devices. ERROR_EXISTS
2024-07-01-02.17.53 Exception occurred: The type initializer for 'Midinous.MIDI.MIDIInfo' threw an exception.
2024-07-01-02.17.53 Caught exception:System.TypeInitializationException: The type initializer for 'Midinous.MIDI.MIDIInfo' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Commons.Music.Midi.MidiAccessManager' threw an exception.
 ---> AlsaSharp.AlsaException: ALSA exception (error code = -2) : No such file or directory
   at AlsaSharp.AlsaSequencer..ctor(AlsaIOType ioType, AlsaIOMode ioMode, String driverName)
   at Commons.Music.Midi.Alsa.AlsaMidiAccess..ctor()
   at Commons.Music.Midi.MidiAccessManager.InitializeDefault()
   at Commons.Music.Midi.MidiAccessManager..cctor()
   --- End of inner exception stack trace ---
   at Commons.Music.Midi.MidiAccessManager.get_Default()
   at Midinous.MIDI.MIDIInfo..cctor()
   --- End of inner exception stack trace ---
   at Midinous.MIDI.MIDIInfo.get_Manager()
   at Midinous.MIDI.MIDIInfo.get_Devices()
   at Midinous.MIDI.MIDIInfo.get_DeviceCount()
   at Midinous.Static.UI.GUI.populate_MIDI_device_selector()
   at Midinous.Static.UI.GUI.show_general()
   at Midinous.Static.UI.GUI.check_options_group(TextButton t)
   at Midinous.Static.UI.GUI.show_options()
   at Midinous.Static.UI.GUI.<>c.<define_main_menu_button_events>b__678_6(Object obj, EventArgs args)
   at Myra.Graphics2D.UI.Widget.OnTouchUp()
   at Myra.Graphics2D.UI.Container.OnTouchUp()
   at Myra.Graphics2D.UI.ButtonBase`1.OnTouchUp()
   at Myra.Utility.InputHelpers.ProcessTouchUp(List`1 widgets)
   at Myra.Graphics2D.UI.Container.OnTouchUp()
   at Myra.Utility.InputHelpers.ProcessTouchUp(List`1 widgets)
   at Myra.Graphics2D.UI.Container.OnTouchUp()
   at Myra.Utility.InputHelpers.ProcessTouchUp(List`1 widgets)
   at Myra.Graphics2D.UI.Container.OnTouchUp()
   at Myra.Utility.InputHelpers.ProcessTouchUp(List`1 widgets)
   at Myra.Graphics2D.UI.Container.OnTouchUp()
   at Myra.Utility.InputHelpers.ProcessTouchUp(List`1 widgets)
   at Myra.Graphics2D.UI.Container.OnTouchUp()
   at Myra.Utility.InputHelpers.ProcessTouchUp(List`1 widgets)
   at Myra.Graphics2D.UI.Container.OnTouchUp()
   at Myra.Utility.InputHelpers.ProcessTouchUp(List`1 widgets)
   at Myra.Graphics2D.UI.Desktop.InputOnTouchUp()
   at Myra.Graphics2D.UI.Desktop.set_IsTouchDown(Boolean value)
   at Myra.Graphics2D.UI.Desktop.UpdateMouseInput()
   at Myra.Graphics2D.UI.Desktop.UpdateInput()
   at Myra.Graphics2D.UI.Desktop.Render()
   at Midinous.Static.UI.GUI.render()
   at Midinous.Base.Midinous.Draw(GameTime progTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Midinous.Base.Program.Main()
2024-07-01-02.17.53 There was an unexpected problem at entry point Program.Main() and the program must close.
```

**Comment by Nornec** [comment]
Have you been able to reproduce this issue consistently?

**Comment by AcidSepp** [comment]
I had the exact same issue. Re-installing steam via apt instead of flatpak fixed it for me.

**Comment by Nornec** [comment]
Thanks for bringing this up. I need to change the error handling around the MIDI device caching. Shouldn't crash the program, should just give an error.

**Comment by Nornec** [comment]
Should be fixed in 1.5.
