### ISSUE TITLE
crash on play

### ISSUE THREAD

**Issue by veksha** [Nornec/Midinous-Issues#66]
project with bug:

[untitled1.json](https://github.com/user-attachments/files/16257242/untitled1.json)

**Comment by veksha** [comment]
```
Application: Midinous.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at Midinous.Core.Actor.create_player(MIDIPoint point, MIDIPoint prev_point)
   at Midinous.Core.Actor.act()
   at Midinous.Static.Performance.run_actors(Dictionary`2 logic_states)
   at Midinous.Static.Performance.start_perform(List`1 start_points)
   at Midinous.Static.Media.Audio.callback_performance_check(Double currentTime)
   at Midinous.Static.Media.Audio.PlayWaveCallback(IntPtr input, IntPtr output, UInt32 frameCount, StreamCallbackTimeInfo& timeInfo, StreamCallbackFlags statusFlags, IntPtr userDataPtr)

```

**Comment by Nornec** [comment]
Please see #64
