### ISSUE TITLE
Note selection crash

### ISSUE THREAD

**Issue by campbellmackinnon** [Nornec/Midinous-Issues#69]
Entering a value above 127 in the highlighted box causes midinous to crash.

![image](https://github.com/user-attachments/assets/6e49b379-eea5-4687-82ca-8eaae9321ac5)

Error log below:
>>>>>>>>2024-09-17-10.11.17 Midinous session startup commencing. This is an error log.
>>>>>>>>2024-09-17-10.11.17 Release - 1.2.1.0
2024-09-17-10.11.41 Exception occurred: Index was outside the bounds of the array.
2024-09-17-10.11.41 Caught exception:System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Midinous.Static.UI.GUI.set_note_selectors(Int32 note_val)
   at Midinous.Static.UI.GUI.prepopulate_spin_buttons[T](Object o)
   at Midinous.Static.UI.GUI.populate_properties(IEnumerable`1 selected)
   at Midinous.Static.UI.GUI.<>c__DisplayClass509_0.<define_spin_button_events>b__12(Object obj, ValueChangedEventArgs`1 args)
   at Myra.Graphics2D.UI.SpinButtonEx.TextBoxOnTextChangedByUser(Object sender, ValueChangedEventArgs`1 eventArgs)
   at Myra.Graphics2D.UI.TextBoxEx.SetText(String value, Boolean byUser)
   at Myra.Graphics2D.UI.TextBoxEx.set_UserText(String value)
   at Myra.Graphics2D.UI.TextBoxEx.InsertChar(Int32 pos, Char ch)
   at Myra.Graphics2D.UI.TextBoxEx.InputChar(Char ch)
   at Myra.Graphics2D.UI.TextBoxEx.OnChar(Char c)
   at Myra.Graphics2D.UI.SpinButtonEx.OnChar(Char c)
   at Myra.Graphics2D.UI.Desktop.OnChar(Char c)
   at Myra.Graphics2D.UI.Desktop.OnKeyDown(Keys key)
   at Myra.Graphics2D.UI.Desktop.UpdateKeyboardInput()
   at Myra.Graphics2D.UI.Desktop.UpdateInput()
   at Myra.Graphics2D.UI.Desktop.Render()
   at Midinous.Static.UI.GUI.render()
   at Midinous.Base.Midinous.Draw(GameTime progTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Midinous.Base.Program.Main()
2024-09-17-10.11.41 There was an unexpected problem at entry point Program.Main() and the program must close.

**Comment by Nornec** [comment]
I do not believe this issue will re-appear in 1.5.
